# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12e17aff9ad1988f48ca6103686f1cd27719d5ee28ca6463f18a00ec69bb3f9b8f5ed30a17f952e06acdc4b963a3e5194c607efbc0d2b1e8e8c3ee61c1664f9a

test:
  secret_key_base: bc909e2974fa88ec1738be635c01117bbe7949b4e8635a1d8221e48693ad3d9003de3291bb76dfe53d1b9a35b8e0025816835b567130bae52be7bfe5503e5ab1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
